# Builder stage
FROM registry.access.redhat.com/ubi9/ubi:9.7 as builder

ARG VERSION=${VERSION}

# 1. Install heavy build dependencies (gcc, rust, etc.)
RUN dnf -y update && \
    dnf -y install \
        wget \
        patch \
        python3.12 \
        python3.12-pip \
        python3.12-devel \
        gcc \
        gcc-c++ \
        rust \
        cargo \
        openssl-devel \
        zlib-devel && \
    dnf clean all

WORKDIR /build

COPY pre-requirements.txt ppc64le.patch ./

# 2. Install Pre-requistes
RUN python3.12 -m pip install -r pre-requirements.txt \
	--extra-index-url=https://wheels.developerfirst.ibm.com/ppc64le/linux/ \
	--prefer-binary

# 3. Set compiler variables for ppc64le
ENV RUSTC_BOOTSTRAP=1 \
    GRPC_PYTHON_BUILD_SYSTEM_OPENSSL=1 \
    GRPC_PYTHON_BUILD_SYSTEM_ZLIB=1

# 4. Download litellm & patch it
RUN wget https://github.com/BerriAI/litellm/archive/refs/tags/v${VERSION}.tar.gz >/dev/null
RUN tar -xzf v${VERSION}.tar.gz && \
    cd litellm-${VERSION} && \
    patch -p1 < ../ppc64le.patch && \
    poetry lock && \
# 5. Export dependencies to a requirements.txt file \
    poetry export -f requirements.txt \
        --without-hashes \
        --only main \
        -E proxy -E semantic-router \
        -o requirements.txt && \
    cat requirements.txt

WORKDIR /build/litellm-${VERSION}

# 6. Compile all dependencies into .whl files
RUN --mount=type=cache,target=/root/.cache/pip \
    python3.12 -m pip wheel -r requirements.txt \
	-w /wheels \
	--extra-index-url=https://wheels.developerfirst.ibm.com/ppc64le/linux/ \
	--prefer-binary && \
    poetry build --format wheel -o /wheels

# Runtime Stage
FROM registry.access.redhat.com/ubi9/ubi-minimal:9.7

ARG VERSION=${VERSION}

RUN --mount=type=bind,from=builder,source=/wheels,target=/wheels,ro \
    microdnf -y update && \
    microdnf -y install \
        python3.12 \
        python3.12-pip && \
    python3.12 -m pip install --no-cache-dir --no-index \
	--find-links=/wheels  \
	litellm[proxy,semantic-router]==${VERSION//-stable} && \
    python3.12 -m pip cache purge && \
    microdnf remove -y python3.12-pip && \
    microdnf clean all 

USER 1001

WORKDIR /app

EXPOSE 4000

# Start the proxy
CMD ["litellm", "--port", "4000"]
